### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by k-kozika**
~~I have updated the microCMS SDK version to the latest 3.1.0.~~
**I forgot to support Content Management API**
Dependency updates as suggested by dependabot were also done.

### CODE REVIEW

**Comment by k-kozika** [comment]
It looks like need to rewrite to the new version, as some of the workflows are using old version... 🤔

**Comment by k-kozika** [comment]
@tsuki-lab
Excuse me for mentioning
I referenced [`createManagementClient` of `microcms-js-sdk`](https://github.com/microcmsio/microcms-js-sdk/blob/f101c9aa29cc2e5360af0dc6160f483499e85d63/src/createManagementClient.ts), but there is no implementations of [the APIs listed in the document](https://document.microcms.io/management-api/introduction).
 Can I implement it here? If so, I'm afraid that if `microcms-js-sdk` implements it differently from us, there will be widespread confusion among users.
Currently, the following solutions are possible:
1. Use [`3.0.0`](https://github.com/microcmsio/microcms-js-sdk/releases/tag/v3.0.0) (does not include `createManagementClient`)
2. Create a type definition with just `makeRequest`

There are possible solutions, but what should we do?

**Comment by tsuki-lab** [comment]
@k-kozika 
thank you.
For this PR, I would like to adopt the idea of 1. for the time being and proceed.

Implementing it independently would certainly cause confusion for users.
So, basically, I would like to proceed to apply only type definitions in `microcms-ts-sdk`.

**Comment by k-kozika** [comment]
> @k-kozika thank you. For this PR, I would like to adopt the idea of 1. for the time being and proceed.

Ok, let's do so

**Review by tsuki-lab — APPROVED** [review]

**Comment by k-kozika** [comment]
Whoa, sorry. I pressed the wrong button by mistake.

**Pull request merged**
